using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._CS.AICore;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._CS.AICore;

[GenerateTypedNameReferences]
public sealed partial class CoyoteAIConfigMenu : FancyWindow
{
    public delegate void SaveDelegate(string name, string personality, string endpoint, string model, string apiKey, float temperature, ReasoningLevel reasoningLevel, string lawSet, int maxHistory, int maxTokens, bool enabled, float visionRange, float cooldownBase, float cooldownCharFactor, float cooldownMax, bool autoContinue, int autoContinueThreshold, int autoContinueMax);
    public event SaveDelegate? OnSave;
    public event Action? OnResetHistory;
    public event Action<int, LogicChannelMode>? OnSetChannel;
    public event Action? OnToggleLock;
    public event Action? OnUnclaim;
    public event Action<string, bool>? OnSetVisionOption;

    private readonly Button[] _channelButtons = new Button[10];
    private LogicChannelMode[] _channelStates = new LogicChannelMode[10];
    private const float ConfirmTimeout = 2f;

    private readonly Dictionary<Button, float> _confirmTimers = new();
    private readonly Dictionary<Button, string> _confirmDefaults = new();
    private readonly Dictionary<Button, Action> _confirmActions = new();

    private bool _advancedExpanded;

    public CoyoteAIConfigMenu()
    {
        RobustXamlLoader.Load(this);

        AiNameEdit.PlaceHolder = "Enter AI name...";
        PersonalityEdit.PlaceHolder = "e.g. A helpful but sardonic overseer";
        MaxHistoryEdit.PlaceHolder = "30";
        MaxTokensEdit.PlaceHolder = "128000";
        VisionRangeEdit.PlaceHolder = "15";
        ApiEndpointEdit.PlaceHolder = "http://localhost:1234/v1/chat/completions";
        ModelNameEdit.PlaceHolder = "e.g. deepseek-v4-flash";
        TemperatureEdit.PlaceHolder = "0.7";

        CooldownBaseEdit.PlaceHolder = "0.3";
        CooldownCharFactorEdit.PlaceHolder = "0.02";
        CooldownMaxEdit.PlaceHolder = "4.0";
        AutoContinueThresholdEdit.PlaceHolder = "400";
        AutoContinueMaxEdit.PlaceHolder = "2";

        LawSetDropdown.OnItemSelected += args =>
        {
            LawSetDropdown.SelectId(args.Id);
        };

        ReasoningDropdown.AddItem("Off");
        ReasoningDropdown.AddItem("Low");
        ReasoningDropdown.AddItem("Medium");
        ReasoningDropdown.AddItem("High");
        ReasoningDropdown.AddItem("Max");
        ReasoningDropdown.SelectId(4);
        ReasoningDropdown.OnItemSelected += args =>
        {
            ReasoningDropdown.SelectId(args.Id);
        };

        AdvancedToggle.OnPressed += _ =>
        {
            _advancedExpanded = !_advancedExpanded;
            AdvancedToggle.Text = _advancedExpanded ? "▲ Advanced Settings" : "▼ Advanced Settings";
            AdvancedSection.Visible = _advancedExpanded;
        };

        CooldownBaseDefault.OnPressed += _ => CooldownBaseEdit.Text = "0.3";
        CooldownCharFactorDefault.OnPressed += _ => CooldownCharFactorEdit.Text = "0.02";
        CooldownMaxDefault.OnPressed += _ => CooldownMaxEdit.Text = "4.0";
        AutoContinueThresholdDefault.OnPressed += _ => AutoContinueThresholdEdit.Text = "400";
        AutoContinueMaxDefault.OnPressed += _ => AutoContinueMaxEdit.Text = "2";

        SaveButton.OnPressed += _ =>
        {
            var name = AiNameEdit.Text.Trim();
            var personality = PersonalityEdit.Text.Trim();
            var endpoint = ApiEndpointEdit.Text.Trim();
            var model = ModelNameEdit.Text.Trim();
            var apiKey = ApiKeyEdit.Text.Trim();
            float.TryParse(TemperatureEdit.Text.Trim(), out var temp);
            if (temp <= 0f) temp = 0.7f;
            if (temp > 2f) temp = 2f;
            int.TryParse(MaxHistoryEdit.Text.Trim(), out var maxHistory);
            if (maxHistory < 5) maxHistory = 30;
            if (maxHistory > 1000) maxHistory = 1000;

            var maxTokensRaw = MaxTokensEdit.Text.Trim();
            int.TryParse(maxTokensRaw, out var maxTokens);
            if (maxTokens < 1) maxTokens = 128000;

            float.TryParse(VisionRangeEdit.Text.Trim(), out var visionRange);
            if (visionRange < 1f) visionRange = 15f;
            if (visionRange > 15f) visionRange = 15f;
            var enabled = EnabledButton.Pressed;
            var reasoning = (ReasoningLevel)ReasoningDropdown.SelectedId;
            var selectedLawSet = LawSetDropdown.ItemCount > 0
                ? (LawSetDropdown.GetItemMetadata(LawSetDropdown.SelectedId) as string) ?? ""
                : "";

            float.TryParse(CooldownBaseEdit.Text.Trim(), out var cdBase);
            if (cdBase <= 0f) cdBase = 0.3f;
            float.TryParse(CooldownCharFactorEdit.Text.Trim(), out var cdFactor);
            if (cdFactor <= 0f) cdFactor = 0.02f;
            float.TryParse(CooldownMaxEdit.Text.Trim(), out var cdMax);
            if (cdMax <= 0f) cdMax = 4f;
            var autoContinue = AutoContinueCheck.Pressed;
            int.TryParse(AutoContinueThresholdEdit.Text.Trim(), out var autoThreshold);
            if (autoThreshold < 50) autoThreshold = 400;
            int.TryParse(AutoContinueMaxEdit.Text.Trim(), out var autoMax);
            if (autoMax < 1) autoMax = 2;

            OnSave?.Invoke(name, personality, endpoint, model, apiKey, temp, reasoning, selectedLawSet, maxHistory, maxTokens, enabled, visionRange, cdBase, cdFactor, cdMax, autoContinue, autoThreshold, autoMax);
        };

        LockButton.OnPressed += _ => OnToggleLock?.Invoke();
        LockedLockButton.OnPressed += _ => OnToggleLock?.Invoke();

        SetupConfirmButton(AbandonButton, "Abandon", () => OnUnclaim?.Invoke());
        SetupConfirmButton(ResetHistoryButton, "Reset History", () => OnResetHistory?.Invoke());
        SetupConfirmButton(LockedAbandonButton, "Abandon", () => OnUnclaim?.Invoke());

        BuildChannelRows();

        VisionPeopleCheck.OnPressed += _ => OnSetVisionOption?.Invoke("ShowPeople", VisionPeopleCheck.Pressed);
        VisionMachinesCheck.OnPressed += _ =>
        {
            OnSetVisionOption?.Invoke("ShowMachines", VisionMachinesCheck.Pressed);
            VisionMachinesDetailCheck.Disabled = !VisionMachinesCheck.Pressed;
        };
        VisionMachinesDetailCheck.OnPressed += _ => OnSetVisionOption?.Invoke("ShowMachinesDetail", VisionMachinesDetailCheck.Pressed);
        VisionItemsCheck.OnPressed += _ =>
        {
            OnSetVisionOption?.Invoke("ShowItems", VisionItemsCheck.Pressed);
            VisionItemsDetailCheck.Disabled = !VisionItemsCheck.Pressed;
        };
        VisionItemsDetailCheck.OnPressed += _ => OnSetVisionOption?.Invoke("ShowItemsDetail", VisionItemsDetailCheck.Pressed);
    }

    private void SetupConfirmButton(Button btn, string defaultText, Action onConfirm)
    {
        _confirmDefaults[btn] = defaultText;
        _confirmActions[btn] = onConfirm;

        btn.OnPressed += _ =>
        {
            if (_confirmTimers.ContainsKey(btn))
            {
                _confirmTimers.Remove(btn);
                btn.Text = defaultText;
                btn.ModulateSelfOverride = null;
                onConfirm();
            }
            else
            {
                _confirmTimers[btn] = ConfirmTimeout;
                btn.Text = "CONFIRM";
                btn.ModulateSelfOverride = Color.Red;
            }
        };
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        List<Button> expired = new();
        foreach (var (btn, timer) in _confirmTimers)
        {
            var newTimer = timer - args.DeltaSeconds;
            if (newTimer <= 0)
            {
                _confirmTimers[btn] = 0;
                expired.Add(btn);
            }
            else
            {
                _confirmTimers[btn] = newTimer;
            }
        }

        foreach (var btn in expired)
        {
            _confirmTimers.Remove(btn);
            if (_confirmDefaults.TryGetValue(btn, out var defaultText))
            {
                btn.Text = defaultText;
                btn.ModulateSelfOverride = null;
            }
        }
    }

    private void BuildChannelRows()
    {
        LogicChannelContainer.Children.Clear();
        for (int i = 0; i < 10; i++)
        {
            var idx = i;
            var name = CoyoteAICoreComponent.LogicChannelNames[i];

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4,
                MinSize = new Vector2(0, 28)
            };

            var labelText = name.Substring(0, 1).ToUpper() + name.Substring(1);
            var label = new Label
            {
                Text = labelText,
                MinSize = new Vector2(60, 0),
                VerticalAlignment = VAlignment.Center
            };

            var offBtn = new Button { Text = "Off", ToggleMode = true, MinSize = new Vector2(45, 24) };
            var onBtn = new Button { Text = "On", ToggleMode = true, MinSize = new Vector2(45, 24) };

            offBtn.OnPressed += _ => SendChannel(idx, LogicChannelMode.Off);
            onBtn.OnPressed += _ => SendChannel(idx, LogicChannelMode.On);

            var sep = new PanelContainer { MinSize = new Vector2(8, 0) };

            var pulseBtn = new Button { Text = "PULSE", MinSize = new Vector2(60, 24) };
            pulseBtn.ModulateSelfOverride = Color.Orange;
            pulseBtn.OnPressed += _ =>
            {
                _channelStates[idx] = LogicChannelMode.Pulse;
                UpdateChannelVisuals(idx);
                OnSetChannel?.Invoke(idx, LogicChannelMode.Pulse);
            };

            row.AddChild(label);
            row.AddChild(offBtn);
            row.AddChild(onBtn);
            row.AddChild(sep);
            row.AddChild(pulseBtn);

            _channelButtons[idx] = offBtn;

            LogicChannelContainer.AddChild(row);
        }
    }

    private void SendChannel(int index, LogicChannelMode mode)
    {
        _channelStates[index] = mode;
        UpdateChannelVisuals(index);
        OnSetChannel?.Invoke(index, mode);
    }

    private void UpdateChannelVisuals(int index)
    {
        var row = LogicChannelContainer.GetChild(index) as BoxContainer;
        if (row == null) return;
        var offBtn = row.GetChild(1) as Button;
        var onBtn = row.GetChild(2) as Button;
        var mode = _channelStates[index];
        offBtn!.Pressed = mode == LogicChannelMode.Off;
        onBtn!.Pressed = mode == LogicChannelMode.On;
    }

private void BuildTokenBar(CoyoteAIConfigBuiState state)
{
    TokenBarContainer.Children.Clear();
    TokenLegendContainer.Children.Clear();

    var totalTokens = state.TotalEstimatedTokens;
    if (totalTokens <= 0)
        return;

    var segments = new (string label, int tokens, Color color)[]
    {
        ("Vision", state.TokenVision, new Color(0.90f, 0.49f, 0.13f)),
        ("System", state.TokenSystem, new Color(0.29f, 0.56f, 0.85f)),
        ("Person/Lore", state.TokenPersonLore, new Color(0.31f, 0.78f, 0.47f)),
        ("Crew/Xeno", state.TokenCrewXeno, new Color(0.96f, 0.65f, 0.14f)),
        ("History", state.TokenHistory, new Color(0.91f, 0.30f, 0.24f)),
        ("Context", state.TokenContext, new Color(0.61f, 0.35f, 0.71f)),
    };

    var barWidth = 680f;
    foreach (var (label, tokens, color) in segments)
    {
        if (tokens <= 0) continue;
        var frac = (float)tokens / totalTokens;
        var seg = new PanelContainer
        {
            MinSize = new Vector2(Math.Max(frac * barWidth, 6), 20),
            ToolTip = $"{label}: ~{tokens} tokens ({frac * 100:F0}%)",
            PanelOverride = new StyleBoxFlat { BackgroundColor = color }
        };
        TokenBarContainer.AddChild(seg);
    }

    foreach (var (label, tokens, color) in segments)
    {
        if (tokens <= 0) continue;
        var frac = (float)tokens / totalTokens;

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 6
        };

        var colorSwatch = new PanelContainer
        {
            MinSize = new Vector2(10, 10),
            VerticalAlignment = VAlignment.Center,
            PanelOverride = new StyleBoxFlat { BackgroundColor = color }
        };

        var labelText = new Label
        {
            Text = $"{label}: ",
            FontColorOverride = Color.Gray
        };

        var valueText = new Label
        {
            Text = $"~{tokens} ({frac * 100:F0}%)",
            FontColorOverride = color
        };

        row.AddChild(colorSwatch);
        row.AddChild(labelText);
        row.AddChild(valueText);
        TokenLegendContainer.AddChild(row);
    }
}

    public void UpdateState(CoyoteAIConfigBuiState state)
    {
        var lockedView = state.LockedView;
        FullView.Visible = !lockedView;
        LockedView.Visible = lockedView;

        if (lockedView)
        {
            SetSize = new Vector2(450, 160);
            LockedOwnerLabel.Text = $"Registered to: {state.OwnerName}";
            LockedStatusLabel.Text = state.IsLocked ? "Status: Locked" : "Status: Unlocked";
            LockedLockButton.Text = state.IsLocked ? "Unlock" : "Lock";
            LockedAbandonButton.Disabled = state.IsLocked;
            return;
        }

        SetSize = new Vector2(740, 840);

        HistoryLabel.Text = $"History messages: {state.HistoryLength}";
        TokenLabel.Text = $"History tokens: ~{state.EstimatedTokens}";
        TotalTokenLabel.Text = $"Total prompt tokens: ~{state.TotalEstimatedTokens}";

        BuildTokenBar(state);

        VisionPeopleCheck.Pressed = state.ShowPeople;
        VisionMachinesCheck.Pressed = state.ShowMachines;
        VisionMachinesDetailCheck.Pressed = state.ShowMachinesDetail;
        VisionMachinesDetailCheck.Disabled = !state.ShowMachines;
        VisionItemsCheck.Pressed = state.ShowItems;
        VisionItemsDetailCheck.Pressed = state.ShowItemsDetail;
        VisionItemsDetailCheck.Disabled = !state.ShowItems;

        if (!state.RefreshOnly)
        {
            AiNameEdit.Text = state.AiName;
            PersonalityEdit.Text = state.PersonalityPrompt;
            MaxHistoryEdit.Text = state.MaxHistory.ToString();
            MaxTokensEdit.Text = state.MaxTokens.ToString();
            VisionRangeEdit.Text = state.VisionRange.ToString("F0");
            ApiEndpointEdit.Text = state.ApiEndpoint;
            ModelNameEdit.Text = state.ModelName;
            TemperatureEdit.Text = state.Temperature.ToString("F1");
            EnabledButton.Pressed = state.Enabled;
            ReasoningDropdown.SelectId((int)state.ReasoningLevelData);

            CooldownBaseEdit.Text = state.CooldownBase.ToString("F1");
            CooldownCharFactorEdit.Text = state.CooldownCharFactor.ToString("F3");
            CooldownMaxEdit.Text = state.CooldownMax.ToString("F1");
            AutoContinueCheck.Pressed = state.AutoContinue;
            AutoContinueThresholdEdit.Text = state.AutoContinueThreshold.ToString();
            AutoContinueMaxEdit.Text = state.AutoContinueMax.ToString();

            LawSetDropdown.Clear();
            var selectedIndex = 0;
            for (int i = 0; i < state.AvailableLawSets.Length; i++)
            {
                var id = state.AvailableLawSets[i];
                var displayName = string.IsNullOrEmpty(id) ? "None" : id;
                var idx = LawSetDropdown.ItemCount;
                LawSetDropdown.AddItem(displayName);
                LawSetDropdown.SetItemMetadata(idx, id);
                if (id == state.LawSet)
                    selectedIndex = idx;
            }
            LawSetDropdown.SelectId(selectedIndex);

            if (state.HasApiKey)
            {
                ApiKeyEdit.PlaceHolder = "API key inserted";
                ApiKeyStatus.Text = "An API key is already configured. Leave empty to keep it.";
            }
            else
            {
                ApiKeyEdit.PlaceHolder = "No API key set";
                ApiKeyStatus.Text = "Enter an API key above to configure one.";
            }
        }

        for (int i = 0; i < 10 && i < state.ChannelStates.Length; i++)
        {
            _channelStates[i] = state.ChannelStates[i];
            UpdateChannelVisuals(i);
        }

        if (state.IsClaimed)
        {
            OwnerLabel.Text = $"Registered to: {state.OwnerName}";
            OwnerLabel.FontColorOverride = Color.Green;
            LockStatusLabel.Text = state.IsLocked ? "Status: Locked" : "Status: Unlocked";
            LockButton.Text = state.IsLocked ? "Unlock" : "Lock";
            LockButton.Disabled = false;
            AbandonButton.Disabled = state.IsLocked;
        }
        else
        {
            OwnerLabel.Text = "Unclaimed - Swipe an ID card to claim";
            OwnerLabel.FontColorOverride = Color.Orange;
            LockStatusLabel.Text = "";
            LockButton.Disabled = true;
            AbandonButton.Disabled = true;
        }
    }
}
