using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._CS.AICore;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._CS.AICore;

[GenerateTypedNameReferences]
public sealed partial class CoyoteAIConfigMenu : FancyWindow
{
    public delegate void SaveDelegate(string name, string personality, string endpoint, string model, string apiKey, float temperature, ReasoningLevel reasoningLevel, string lawSet, int maxHistory, int maxTokens, bool enabled, float visionRange, float cooldownBase, float cooldownCharFactor, float cooldownMax, bool autoContinue, int autoContinueThreshold, int autoContinueMax, List<AICoreMemory>? memories, ItemVisionMode localItemMode, string[] channelLabels);
    public event SaveDelegate? OnSave;
    public event Action? OnResetHistory;
    public event Action<int, LogicChannelMode>? OnSetChannel;
    public event Action<int, string>? OnSetChannelLabel;
    public event Action? OnToggleLock;
    public event Action? OnUnclaim;
    public event Action<string, bool>? OnSetVisionOption;
    public event Action<ItemVisionMode>? OnSetItemMode;
    public event Action<string, bool>? OnSetGlobalVisionOption;
    public event Action<ItemVisionMode>? OnSetGlobalItemMode;
    public event Action<string, bool>? OnSetCameraSubnet;
    public event Action<bool>? OnSetEnabled;
    public event Action<string, bool>? OnSetRadioChannel;
    public event Action? OnExport;
    public event Action<string>? OnImport;
    public event Action<string, MemoryPriority, List<string>>? OnAddMemory;
    public event Action<string>? OnRemoveMemory;

    private readonly Button[] _channelPulseButtons = new Button[20];
    private readonly LineEdit[] _channelLabelEdits = new LineEdit[20];
    private LogicChannelMode[] _channelStates = new LogicChannelMode[20];
    private string[] _channelLabels = new string[20];
    private const float ConfirmTimeout = 2f;

    private readonly Dictionary<Button, float> _confirmTimers = new();
    private readonly Dictionary<Button, string> _confirmDefaults = new();
    private readonly Dictionary<Button, Action> _confirmActions = new();
    private readonly Dictionary<string, CheckBox> _radioChannelChecks = new();
    private readonly Dictionary<string, CheckBox> _cameraSubnetChecks = new();

    private bool _advancedExpanded;
    private bool _visionExpanded = true;
    private bool _radioExpanded = true;
    private bool _logicChannelsExpanded;
    private List<AICoreMemory> _memories = new();
    private readonly HashSet<string> _expandedMemoryIds = new();

    public CoyoteAIConfigMenu()
    {
        RobustXamlLoader.Load(this);

        AiNameEdit.PlaceHolder = "Enter AI name...";
        PersonalityEdit.PlaceHolder = "e.g. A helpful but sardonic overseer";
        MaxHistoryEdit.PlaceHolder = "200";
        MaxTokensEdit.PlaceHolder = "128000";
        VisionRangeEdit.PlaceHolder = "15";
        ApiEndpointEdit.PlaceHolder = "http://localhost:1234/v1/chat/completions";
        ModelNameEdit.PlaceHolder = "e.g. deepseek-v4-flash";
        TemperatureEdit.PlaceHolder = "0.7";

        CooldownBaseEdit.PlaceHolder = "0.3";
        CooldownCharFactorEdit.PlaceHolder = "0.02";
        CooldownMaxEdit.PlaceHolder = "4.0";
        AutoContinueThresholdEdit.PlaceHolder = "400";
        AutoContinueMaxEdit.PlaceHolder = "2";

        LawSetDropdown.OnItemSelected += args =>
        {
            LawSetDropdown.SelectId(args.Id);
        };

        ReasoningDropdown.AddItem("Off");
        ReasoningDropdown.AddItem("Low");
        ReasoningDropdown.AddItem("Medium");
        ReasoningDropdown.AddItem("High");
        ReasoningDropdown.AddItem("Max");
        ReasoningDropdown.SelectId(4);
        ReasoningDropdown.OnItemSelected += args =>
        {
            ReasoningDropdown.SelectId(args.Id);
        };

        AdvancedToggle.OnPressed += _ =>
        {
            _advancedExpanded = !_advancedExpanded;
            AdvancedToggle.Text = _advancedExpanded ? "▲ Advanced Settings" : "▼ Advanced Settings";
            AdvancedSection.Visible = _advancedExpanded;
        };

        CooldownBaseDefault.OnPressed += _ => CooldownBaseEdit.Text = "0.3";
        CooldownCharFactorDefault.OnPressed += _ => CooldownCharFactorEdit.Text = "0.02";
        CooldownMaxDefault.OnPressed += _ => CooldownMaxEdit.Text = "4.0";
        AutoContinueThresholdDefault.OnPressed += _ => AutoContinueThresholdEdit.Text = "400";
        AutoContinueMaxDefault.OnPressed += _ => AutoContinueMaxEdit.Text = "2";

        SaveButton.OnPressed += _ => PerformSave();

        LockButton.OnPressed += _ => OnToggleLock?.Invoke();
        LockedLockButton.OnPressed += _ => OnToggleLock?.Invoke();
        EnabledButton.OnPressed += _ => OnSetEnabled?.Invoke(EnabledButton.Pressed);

        SetupConfirmButton(AbandonButton, "Abandon", () => OnUnclaim?.Invoke());
        SetupConfirmButton(ResetHistoryButton, "Reset History", () => OnResetHistory?.Invoke());
        SetupConfirmButton(LockedAbandonButton, "Abandon", () => OnUnclaim?.Invoke());

        ExportButton.OnPressed += _ => OnExport?.Invoke();
        ImportButton.OnPressed += _ =>
        {
            PerformSave();
            OnImport?.Invoke("trigger");
        };

        MemoryPriorityDropdown.AddItem("Low");
        MemoryPriorityDropdown.AddItem("Normal");
        MemoryPriorityDropdown.AddItem("High");
        MemoryPriorityDropdown.SelectId(1);
        MemoryPriorityDropdown.OnItemSelected += args =>
        {
            MemoryPriorityDropdown.SelectId(args.Id);
        };

        AddMemoryButton.OnPressed += _ =>
        {
            var content = NewMemoryEdit.Text.Trim();
            if (string.IsNullOrEmpty(content)) return;
            var priority = (MemoryPriority)MemoryPriorityDropdown.SelectedId;
            OnAddMemory?.Invoke(content, priority, new());
            NewMemoryEdit.Text = "";
        };

        BuildChannelRows();

        // Local vision wiring
        VisionPeopleLocalCheck.OnPressed += _ => OnSetVisionOption?.Invoke("ShowPeople", VisionPeopleLocalCheck.Pressed);
        VisionMachinesLocalCheck.OnPressed += _ =>
        {
            OnSetVisionOption?.Invoke("ShowMachines", VisionMachinesLocalCheck.Pressed);
            VisionMachinesDetailLocalCheck.Disabled = !VisionMachinesLocalCheck.Pressed;
        };
        VisionMachinesDetailLocalCheck.OnPressed += _ => OnSetVisionOption?.Invoke("ShowMachinesDetail", VisionMachinesDetailLocalCheck.Pressed);
        VisionItemsLocalCheck.OnPressed += _ =>
        {
            OnSetVisionOption?.Invoke("ShowItems", VisionItemsLocalCheck.Pressed);
            VisionItemsDetailLocalCheck.Disabled = !VisionItemsLocalCheck.Pressed;
        };
        VisionItemsDetailLocalCheck.OnPressed += _ => OnSetVisionOption?.Invoke("ShowItemsDetail", VisionItemsDetailLocalCheck.Pressed);

        LocalItemModeDropdown.AddItem("Feed All");
        LocalItemModeDropdown.AddItem("Smart Summary");
        LocalItemModeDropdown.AddItem("Search Engine");
        LocalItemModeDropdown.SelectId(2);
        LocalItemModeDropdown.OnItemSelected += args =>
        {
            LocalItemModeDropdown.SelectId(args.Id);
            var mode = (ItemVisionMode)args.Id;
            LocalItemDetailCheckContainer.Visible = mode == ItemVisionMode.FeedAll;
            OnSetItemMode?.Invoke(mode);
        };

        // Global vision wiring
        GlobalVisionEnabledCheck.OnPressed += _ => OnSetGlobalVisionOption?.Invoke("GlobalVisionEnabled", GlobalVisionEnabledCheck.Pressed);
        VisionPeopleGlobalCheck.OnPressed += _ => OnSetGlobalVisionOption?.Invoke("ShowPeopleGlobal", VisionPeopleGlobalCheck.Pressed);
        VisionMachinesGlobalCheck.OnPressed += _ =>
        {
            OnSetGlobalVisionOption?.Invoke("ShowMachinesGlobal", VisionMachinesGlobalCheck.Pressed);
            VisionMachinesDetailGlobalCheck.Disabled = !VisionMachinesGlobalCheck.Pressed;
        };
        VisionMachinesDetailGlobalCheck.OnPressed += _ => OnSetGlobalVisionOption?.Invoke("ShowMachinesDetailGlobal", VisionMachinesDetailGlobalCheck.Pressed);
        VisionItemsGlobalCheck.OnPressed += _ =>
        {
            OnSetGlobalVisionOption?.Invoke("ShowItemsGlobal", VisionItemsGlobalCheck.Pressed);
            VisionItemsDetailGlobalCheck.Disabled = !VisionItemsGlobalCheck.Pressed;
        };
        VisionItemsDetailGlobalCheck.OnPressed += _ => OnSetGlobalVisionOption?.Invoke("ShowItemsDetailGlobal", VisionItemsDetailGlobalCheck.Pressed);

        GlobalItemModeDropdown.AddItem("Feed All");
        GlobalItemModeDropdown.AddItem("Smart Summary");
        GlobalItemModeDropdown.AddItem("Search Engine");
        GlobalItemModeDropdown.SelectId(2);
        GlobalItemModeDropdown.OnItemSelected += args =>
        {
            GlobalItemModeDropdown.SelectId(args.Id);
            var mode = (ItemVisionMode)args.Id;
            GlobalItemDetailCheckContainer.Visible = mode == ItemVisionMode.FeedAll;
            OnSetGlobalItemMode?.Invoke(mode);
        };

        VisionToggle.OnPressed += _ =>
        {
            _visionExpanded = !_visionExpanded;
            VisionToggle.Text = _visionExpanded ? "▼ VISION" : "▶ VISION";
            VisionSection.Visible = _visionExpanded;
        };

        LogicChannelsToggle.OnPressed += _ =>
        {
            _logicChannelsExpanded = !_logicChannelsExpanded;
            LogicChannelsToggle.Text = _logicChannelsExpanded ? "▼ LOGIC CHANNELS" : "▶ LOGIC CHANNELS";
            LogicChannelsSection.Visible = _logicChannelsExpanded;
        };

        RadioToggle.OnPressed += _ =>
        {
            _radioExpanded = !_radioExpanded;
            RadioToggle.Text = _radioExpanded ? "▼ RADIO" : "▶ RADIO";
            RadioSection.Visible = _radioExpanded;
        };

        BuildRadioCheckboxes();
    }

    private void PerformSave()
    {
        var name = AiNameEdit.Text.Trim();
        var personality = PersonalityEdit.Text.Trim();
        var endpoint = ApiEndpointEdit.Text.Trim();
        var model = ModelNameEdit.Text.Trim();
        var apiKey = ApiKeyEdit.Text.Trim();
        float.TryParse(TemperatureEdit.Text.Trim(), out var temp);
        if (temp <= 0f) temp = 0.7f;
        if (temp > 2f) temp = 2f;
        int.TryParse(MaxHistoryEdit.Text.Trim(), out var maxHistory);
        if (maxHistory < 5) maxHistory = 200;
        if (maxHistory > 1000) maxHistory = 1000;

        var maxTokensRaw = MaxTokensEdit.Text.Trim();
        int.TryParse(maxTokensRaw, out var maxTokens);
        if (maxTokens < 1) maxTokens = 128000;

        float.TryParse(VisionRangeEdit.Text.Trim(), out var visionRange);
        if (visionRange < 1f) visionRange = 15f;
        if (visionRange > 15f) visionRange = 15f;
        var enabled = EnabledButton.Pressed;
        var reasoning = (ReasoningLevel)ReasoningDropdown.SelectedId;
        var selectedLawSet = LawSetDropdown.ItemCount > 0
            ? (LawSetDropdown.GetItemMetadata(LawSetDropdown.SelectedId) as string) ?? ""
            : "";

        float.TryParse(CooldownBaseEdit.Text.Trim(), out var cdBase);
        if (cdBase <= 0f) cdBase = 0.3f;
        float.TryParse(CooldownCharFactorEdit.Text.Trim(), out var cdFactor);
        if (cdFactor <= 0f) cdFactor = 0.02f;
        float.TryParse(CooldownMaxEdit.Text.Trim(), out var cdMax);
        if (cdMax <= 0f) cdMax = 4f;
        var autoContinue = AutoContinueCheck.Pressed;
        int.TryParse(AutoContinueThresholdEdit.Text.Trim(), out var autoThreshold);
        if (autoThreshold < 50) autoThreshold = 400;
        int.TryParse(AutoContinueMaxEdit.Text.Trim(), out var autoMax);
        if (autoMax < 1) autoMax = 2;

        var labels = new string[20];
        for (int i = 0; i < 20; i++)
            labels[i] = _channelLabelEdits[i]?.Text ?? string.Empty;

        OnSave?.Invoke(name, personality, endpoint, model, apiKey, temp, reasoning, selectedLawSet, maxHistory, maxTokens, enabled, visionRange, cdBase, cdFactor, cdMax, autoContinue, autoThreshold, autoMax, _memories, (ItemVisionMode)LocalItemModeDropdown.SelectedId, labels);
    }

    private void SetupConfirmButton(Button btn, string defaultText, Action onConfirm)
    {
        _confirmDefaults[btn] = defaultText;
        _confirmActions[btn] = onConfirm;

        btn.OnPressed += _ =>
        {
            if (_confirmTimers.ContainsKey(btn))
            {
                _confirmTimers.Remove(btn);
                btn.Text = defaultText;
                btn.ModulateSelfOverride = null;
                onConfirm();
            }
            else
            {
                _confirmTimers[btn] = ConfirmTimeout;
                btn.Text = "CONFIRM";
                btn.ModulateSelfOverride = Color.Red;
            }
        };
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        List<Button> expired = new();
        foreach (var (btn, timer) in _confirmTimers)
        {
            var newTimer = timer - args.DeltaSeconds;
            if (newTimer <= 0)
            {
                _confirmTimers[btn] = 0;
                expired.Add(btn);
            }
            else
            {
                _confirmTimers[btn] = newTimer;
            }
        }

        foreach (var btn in expired)
        {
            _confirmTimers.Remove(btn);
            if (_confirmDefaults.TryGetValue(btn, out var defaultText))
            {
                btn.Text = defaultText;
                btn.ModulateSelfOverride = null;
            }
        }
    }

    private void BuildChannelRows()
    {
        LogicChannelContainer.Children.Clear();
        for (int i = 0; i < 20; i++)
        {
            var idx = i;
            var name = CoyoteAICoreComponent.LogicChannelNames[i];
            var labelText = name.Substring(0, 1).ToUpper() + name.Substring(1);

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4,
                MinSize = new Vector2(0, 28)
            };

            var label = new Label
            {
                Text = labelText,
                MinSize = new Vector2(100, 0),
                VerticalAlignment = VAlignment.Center
            };

            var labelEdit = new LineEdit
            {
                PlaceHolder = name,
                MinSize = new Vector2(120, 24),
                HorizontalExpand = true,
            };
            labelEdit.OnTextChanged += args =>
            {
                _channelLabels[idx] = args.Text ?? string.Empty;
                OnSetChannelLabel?.Invoke(idx, args.Text ?? string.Empty);
            };
            _channelLabelEdits[idx] = labelEdit;

            var pulseBtn = new Button { Text = "PULSE", MinSize = new Vector2(70, 24) };
            pulseBtn.ModulateSelfOverride = Color.Orange;
            pulseBtn.OnPressed += _ =>
            {
                _channelStates[idx] = LogicChannelMode.Pulse;
                OnSetChannel?.Invoke(idx, LogicChannelMode.Pulse);
            };
            _channelPulseButtons[idx] = pulseBtn;

            row.AddChild(label);
            row.AddChild(labelEdit);
            row.AddChild(pulseBtn);
            LogicChannelContainer.AddChild(row);
        }
    }

    private void UpdateChannelVisuals(int index)
    {
    }

    private void BuildRadioCheckboxes()
    {
        RadioChannelContainer.Children.Clear();
        _radioChannelChecks.Clear();

        var rowContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 2
        };

        foreach (var ch in CoyoteAICoreComponent.AvailableRadioChannels)
        {
            var check = new CheckBox
            {
                Text = ch,
                Pressed = true
            };
            check.OnPressed += _ =>
            {
                OnSetRadioChannel?.Invoke(ch, check.Pressed);
            };
            _radioChannelChecks[ch] = check;
            rowContainer.AddChild(check);
        }

        RadioChannelContainer.AddChild(rowContainer);
    }

    private void BuildCameraSubnetCheckboxes(Dictionary<string, int> availableSubnets, HashSet<string> enabledSubnets)
    {
        GlobalCameraSubnetContainer.Children.Clear();
        _cameraSubnetChecks.Clear();

        if (availableSubnets.Count == 0)
        {
            GlobalCameraSubnetContainer.AddChild(new Label
            {
                Text = "No cameras detected on current grid.",
                FontColorOverride = Color.Gray
            });
            return;
        }

        foreach (var (subnetId, cameraCount) in availableSubnets.OrderBy(kv => kv.Key))
        {
            var subnetName = subnetId.Replace("SurveillanceCamera", "");
            var check = new CheckBox
            {
                Text = $"{subnetName} ({cameraCount} cameras)",
                Pressed = enabledSubnets.Contains(subnetId)
            };
            var capturedId = subnetId;
            check.OnPressed += _ =>
            {
                OnSetCameraSubnet?.Invoke(capturedId, check.Pressed);
            };
            _cameraSubnetChecks[subnetId] = check;
            GlobalCameraSubnetContainer.AddChild(check);
        }
    }

    private void BuildTokenBar(CoyoteAIConfigBuiState state)
    {
        TokenBarContainer.Children.Clear();
        TokenLegendContainer.Children.Clear();

        var totalTokens = state.TotalEstimatedTokens;
        if (totalTokens <= 0)
            return;

        var segments = new (string label, int tokens, Color color)[]
        {
            ("Local Vision", state.TokenLocalVision, new Color(0.90f, 0.49f, 0.13f)),
            ("Global Vision", state.TokenGlobalVision, new Color(0.95f, 0.75f, 0.05f)),
            ("System", state.TokenSystem, new Color(0.29f, 0.56f, 0.85f)),
            ("Person/Lore", state.TokenPersonLore, new Color(0.31f, 0.78f, 0.47f)),
            ("Crew/Xeno", state.TokenCrewXeno, new Color(0.96f, 0.65f, 0.14f)),
            ("History", state.TokenHistory, new Color(0.91f, 0.30f, 0.24f)),
            ("Context", state.TokenContext, new Color(0.61f, 0.35f, 0.71f)),
        };

        var barWidth = 680f;
        foreach (var (label, tokens, color) in segments)
        {
            if (tokens <= 0) continue;
            var frac = (float)tokens / totalTokens;
            var seg = new PanelContainer
            {
                MinSize = new Vector2(Math.Max(frac * barWidth, 6), 20),
                ToolTip = $"{label}: ~{tokens} tokens ({frac * 100:F0}%)",
                PanelOverride = new StyleBoxFlat { BackgroundColor = color }
            };
            TokenBarContainer.AddChild(seg);
        }

        foreach (var (label, tokens, color) in segments)
        {
            if (tokens <= 0) continue;
            var frac = (float)tokens / totalTokens;

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 6
            };

            var colorSwatch = new PanelContainer
            {
                MinSize = new Vector2(10, 10),
                VerticalAlignment = VAlignment.Center,
                PanelOverride = new StyleBoxFlat { BackgroundColor = color }
            };

            var labelText = new Label
            {
                Text = $"{label}: ",
                FontColorOverride = Color.Gray
            };

            var valueText = new Label
            {
                Text = $"~{tokens} ({frac * 100:F0}%)",
                FontColorOverride = color
            };

            row.AddChild(colorSwatch);
            row.AddChild(labelText);
            row.AddChild(valueText);
            TokenLegendContainer.AddChild(row);
        }
    }

    private void BuildMemoryRows()
    {
        MemoriesContainer.Children.Clear();
        foreach (var mem in _memories)
        {
            var memId = mem.Id;
            var alreadyExpanded = _expandedMemoryIds.Contains(memId);
            var fullText = $"[{mem.Priority}] {mem.Content}";
            var collapsedText = fullText.Length > 80 ? fullText[..77] + "..." : fullText;

            var expandBtn = new Button
            {
                Text = alreadyExpanded ? "▲" : "▼",
                MinSize = new Vector2(24, 24),
            };

            var deleteBtn = new Button
            {
                Text = "X",
                MinSize = new Vector2(30, 24),
            };
            deleteBtn.OnPressed += _ => OnRemoveMemory?.Invoke(memId);

            expandBtn.OnPressed += _ =>
            {
                if (_expandedMemoryIds.Contains(memId))
                    _expandedMemoryIds.Remove(memId);
                else
                    _expandedMemoryIds.Add(memId);
                BuildMemoryRows();
            };

            if (alreadyExpanded)
            {
                var contentLabel = new Label
                {
                    Text = WordWrap(fullText, 60),
                    HorizontalExpand = true,
                    VerticalAlignment = VAlignment.Top,
                    ClipText = false
                };
                var btnRow = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    SeparationOverride = 4,
                    MinSize = new Vector2(0, 28)
                };
                btnRow.AddChild(expandBtn);
                btnRow.AddChild(deleteBtn);

                var row = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    SeparationOverride = 2
                };
                row.AddChild(contentLabel);
                row.AddChild(btnRow);
                MemoriesContainer.AddChild(row);
            }
            else
            {
                var contentLabel = new Label
                {
                    Text = collapsedText,
                    HorizontalExpand = true,
                    VerticalAlignment = VAlignment.Center,
                    ClipText = true
                };
                var row = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    SeparationOverride = 4,
                    MinSize = new Vector2(0, 28)
                };
                row.AddChild(contentLabel);
                row.AddChild(expandBtn);
                row.AddChild(deleteBtn);
                MemoriesContainer.AddChild(row);
            }
        }
    }

    private static string WordWrap(string text, int maxCharsPerLine)
    {
        if (string.IsNullOrEmpty(text) || text.Length <= maxCharsPerLine)
            return text;

        var sb = new System.Text.StringBuilder();
        var start = 0;
        while (start < text.Length)
        {
            if (start + maxCharsPerLine >= text.Length)
            {
                sb.Append(text[start..]);
                break;
            }

            var end = start + maxCharsPerLine;
            var breakAt = text.LastIndexOfAny(new[] { ' ', ',', '.', ';', ':', '-', '/' }, end, maxCharsPerLine);
            if (breakAt <= start)
                breakAt = end;
            else
                breakAt++;

            sb.Append(text[start..breakAt]);
            sb.Append('\n');
            start = breakAt;
        }
        return sb.ToString();
    }

    public void UpdateState(CoyoteAIConfigBuiState state)
    {
        var lockedView = state.LockedView;
        FullView.Visible = !lockedView;
        LockedView.Visible = lockedView;

        if (lockedView)
        {
            SetSize = new Vector2(450, 160);

            if (string.IsNullOrEmpty(state.OwnerName))
            {
                LockedOwnerLabel.Text = "Unclaimed - Swipe an ID card to claim";
                LockedOwnerLabel.FontColorOverride = Color.Orange;
            }
            else
            {
                LockedOwnerLabel.Text = $"Registered to: {state.OwnerName}";
                LockedOwnerLabel.FontColorOverride = Color.Green;
            }

            if (state.AiLocked)
            {
                LockedStatusLabel.Text = "Status: AI-Locked";
                LockedStatusLabel.FontColorOverride = Color.Cyan;
                LockedLockButton.Disabled = true;
            }
            else
            {
                LockedStatusLabel.Text = state.IsLocked ? "Status: Locked" : "Status: Unlocked";
                LockedStatusLabel.FontColorOverride = state.IsLocked ? Color.Green : Color.Gray;
                LockedLockButton.Disabled = false;
            }

            LockedLockButton.Text = state.IsLocked ? "Unlock" : "Lock";
            LockedAbandonButton.Disabled = state.IsLocked || !state.IsClaimed;
            return;
        }

        SetSize = new Vector2(740, 840);

        HistoryLabel.Text = $"History messages: {state.HistoryLength}";
        TokenLabel.Text = $"History tokens: ~{state.EstimatedTokens}";
        TotalTokenLabel.Text = $"Total prompt tokens: ~{state.TotalEstimatedTokens}";

        BuildTokenBar(state);

        // Ship & load display
        if (!string.IsNullOrEmpty(state.OriginalShipName) || !string.IsNullOrEmpty(state.CurrentShipName))
        {
            ShipLabel.Text = $"Vessel: {state.CurrentShipName} (built: {state.OriginalShipName})";
        }
        else
        {
            ShipLabel.Text = "";
        }

        if (state.LoadCount > 0)
        {
            LoadLabel.Text = $"Loads: {state.LoadCount} | {state.LoadTimestampsDisplay}";
        }
        else
        {
            LoadLabel.Text = "";
        }

        // Memories
        _memories = state.Memories;
        _expandedMemoryIds.RemoveWhere(id => !_memories.Any(m => m.Id == id));
        BuildMemoryRows();

        // Local vision
        VisionPeopleLocalCheck.Pressed = state.ShowPeopleLocal;
        VisionMachinesLocalCheck.Pressed = state.ShowMachinesLocal;
        VisionMachinesDetailLocalCheck.Pressed = state.ShowMachinesDetailLocal;
        VisionMachinesDetailLocalCheck.Disabled = !state.ShowMachinesLocal;
        VisionItemsLocalCheck.Pressed = state.ShowItemsLocal;
        VisionItemsDetailLocalCheck.Pressed = state.ShowItemsDetailLocal;
        VisionItemsDetailLocalCheck.Disabled = !state.ShowItemsLocal;

        // Global vision
        GlobalVisionEnabledCheck.Pressed = state.GlobalVisionEnabled;
        VisionPeopleGlobalCheck.Pressed = state.ShowPeopleGlobal;
        VisionMachinesGlobalCheck.Pressed = state.ShowMachinesGlobal;
        VisionMachinesDetailGlobalCheck.Pressed = state.ShowMachinesDetailGlobal;
        VisionMachinesDetailGlobalCheck.Disabled = !state.ShowMachinesGlobal;
        VisionItemsGlobalCheck.Pressed = state.ShowItemsGlobal;
        VisionItemsDetailGlobalCheck.Pressed = state.ShowItemsDetailGlobal;
        VisionItemsDetailGlobalCheck.Disabled = !state.ShowItemsGlobal;

        // Global subnet checkboxes
        BuildCameraSubnetCheckboxes(state.AvailableCameraSubnets, state.EnabledCameraSubnets);

        if (!state.RefreshOnly)
        {
            AiNameEdit.Text = state.AiName;
            PersonalityEdit.Text = state.PersonalityPrompt;
            MaxHistoryEdit.Text = state.MaxHistory.ToString();
            MaxTokensEdit.Text = state.MaxTokens.ToString();
            VisionRangeEdit.Text = state.VisionRange.ToString("F0");
            ApiEndpointEdit.Text = state.ApiEndpoint;
            ModelNameEdit.Text = state.ModelName;
            TemperatureEdit.Text = state.Temperature.ToString("F1");
            EnabledButton.Pressed = state.Enabled;
            ReasoningDropdown.SelectId((int)state.ReasoningLevelData);

            LocalItemModeDropdown.SelectId((int)state.LocalItemMode);
            LocalItemDetailCheckContainer.Visible = state.LocalItemMode == ItemVisionMode.FeedAll;

            GlobalItemModeDropdown.SelectId((int)state.GlobalItemMode);
            GlobalItemDetailCheckContainer.Visible = state.GlobalItemMode == ItemVisionMode.FeedAll;

            CooldownBaseEdit.Text = state.CooldownBase.ToString("F1");
            CooldownCharFactorEdit.Text = state.CooldownCharFactor.ToString("F3");
            CooldownMaxEdit.Text = state.CooldownMax.ToString("F1");
            AutoContinueCheck.Pressed = state.AutoContinue;
            AutoContinueThresholdEdit.Text = state.AutoContinueThreshold.ToString();
            AutoContinueMaxEdit.Text = state.AutoContinueMax.ToString();

            LawSetDropdown.Clear();
            var selectedIndex = 0;
            for (int i = 0; i < state.AvailableLawSets.Length; i++)
            {
                var id = state.AvailableLawSets[i];
                var displayName = string.IsNullOrEmpty(id) ? "None" : id;
                var idx = LawSetDropdown.ItemCount;
                LawSetDropdown.AddItem(displayName);
                LawSetDropdown.SetItemMetadata(idx, id);
                if (id == state.LawSet)
                    selectedIndex = idx;
            }
            LawSetDropdown.SelectId(selectedIndex);

            if (state.HasApiKey)
            {
                ApiKeyEdit.PlaceHolder = "API key inserted";
                ApiKeyStatus.Text = "An API key is already configured. Leave empty to keep it.";
            }
            else
            {
                ApiKeyEdit.PlaceHolder = "No API key set";
                ApiKeyStatus.Text = "Enter an API key above to configure one.";
            }
        }

        foreach (var ch in CoyoteAICoreComponent.AvailableRadioChannels)
        {
            if (_radioChannelChecks.TryGetValue(ch, out var check))
                check.Pressed = state.RadioChannels.Contains(ch);
        }

        for (int i = 0; i < 20 && i < state.ChannelStates.Length; i++)
        {
            _channelStates[i] = state.ChannelStates[i];
            UpdateChannelVisuals(i);
        }

        if (state.ChannelLabels != null)
        {
            for (int i = 0; i < 20 && i < state.ChannelLabels.Length; i++)
            {
                _channelLabels[i] = state.ChannelLabels[i];
                if (!state.RefreshOnly && _channelLabelEdits[i] != null)
                    _channelLabelEdits[i].Text = state.ChannelLabels[i] ?? string.Empty;
            }
        }

        if (state.IsClaimed)
        {
            OwnerLabel.Text = $"Registered to: {state.OwnerName}";
            OwnerLabel.FontColorOverride = Color.Green;
            if (state.AiLocked)
            {
                LockStatusLabel.Text = "Status: AI-Locked";
                LockStatusLabel.FontColorOverride = Color.Cyan;
                LockButton.Text = "Locked by AI";
                LockButton.Disabled = true;
                AbandonButton.Disabled = true;
            }
            else
            {
                LockStatusLabel.Text = state.IsLocked ? "Status: Locked" : "Status: Unlocked";
                LockStatusLabel.FontColorOverride = state.IsLocked ? Color.Green : Color.Gray;
                LockButton.Text = state.IsLocked ? "Unlock" : "Lock";
                LockButton.Disabled = false;
                AbandonButton.Disabled = state.IsLocked;
            }
        }
        else if (state.AiLocked)
        {
            OwnerLabel.Text = "Unclaimed - Swipe an ID card to claim";
            OwnerLabel.FontColorOverride = Color.Orange;
            LockStatusLabel.Text = "Status: AI-Locked";
            LockStatusLabel.FontColorOverride = Color.Cyan;
            LockButton.Text = "Locked by AI";
            LockButton.Disabled = true;
            AbandonButton.Disabled = true;
        }
        else
        {
            OwnerLabel.Text = "Unclaimed - Swipe an ID card to claim";
            OwnerLabel.FontColorOverride = Color.Orange;
            LockStatusLabel.Text = "";
            LockButton.Disabled = true;
            AbandonButton.Disabled = true;
        }
    }
}
